name: PlayerShops
version: 1.2
description: A simple shop based plugin
author: AssasinTreepig
main: shops.PlayerShops
commands:
    shop:
      description: teleports you to the shop
    playershops:
      description: gives information about playershops
Permissions:
   shop.teleport:
     default: op
   shop.set:
     default: op
   shop.close:
     default: op
   shop.open:
     default: op
   shop.reload:
     default: op
   playershops.create:
     default: op
